services:
  api:
    build: .
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=host=db user=postgres password=postgres dbname=interview_db port=5432 sslmode=disable
    depends_on:
      - db
    networks:
      - interview-network
    command: make -e dev      
    volumes:
      - .:/app:delegated
      - go-pkg-cache:/go/pkg:cache
      - go-build-cache:/go/cache/go-build:cache
  db:
    image: postgres:17
    environment:
      - POSTGRES_DB=interview_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - interview-network

volumes:
  postgres_data:
  go-pkg-cache:
  go-build-cache:

networks:
  interview-network:
    driver: bridge
